# Generated by Django 5.2.11 on 2026-07-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CdekDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdek_office_code_from', models.CharField(blank=True, max_length=255, null=True)),
                ('cdek_office_code_to', models.CharField(blank=True, max_length=255, null=True)),
                ('tariff_code', models.IntegerField(blank=True, null=True)),
                ('cdek_uuid', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('preliminary_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shipment_track_id', models.BigIntegerField(blank=True, null=True)),
                ('shipment_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order_status', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.PositiveSmallIntegerField(choices=[(1, 'СДЭК')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
