# Generated by Django 5.2.11 on 2026-07-17 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0002_initial'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdelivery',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='seller.shop'),
        ),
        migrations.AddField(
            model_name='cdekdelivery',
            name='order_delivery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cdek', to='delivery.orderdelivery'),
        ),
    ]
