# Generated by Django 5.2.11 on 2026-07-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDEKTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_code', models.PositiveIntegerField(unique=True, verbose_name='Код тарифа')),
                ('tariff_name', models.CharField(max_length=255, verbose_name='Название тарифа')),
                ('delivery_mode', models.PositiveSmallIntegerField(verbose_name='Код режима доставки')),
                ('delivery_mode_name', models.CharField(max_length=50, verbose_name='Режим доставки')),
                ('weight_min', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Минимальный вес')),
                ('weight_max', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Максимальный вес')),
                ('length_max', models.PositiveIntegerField(verbose_name='Максимальная длина')),
                ('width_max', models.PositiveIntegerField(verbose_name='Максимальная ширина')),
                ('height_max', models.PositiveIntegerField(verbose_name='Максимальная высота')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тариф CDEK',
                'verbose_name_plural': 'Тарифы CDEK',
                'ordering': ('tariff_name', 'tariff_code'),
            },
        ),
    ]
