# Generated by Django 5.2.11 on 2026-07-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_cdektariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdektariff',
            name='weight_max',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Максимальный вес'),
        ),
        migrations.AlterField(
            model_name='cdektariff',
            name='weight_min',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Минимальный вес'),
        ),
    ]
