# Generated by Django 5.2.11 on 2026-08-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_cdektariff_weight_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdelivery',
            name='delivery_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'СДЭК'), (2, 'Boxberry')]),
        ),
    ]
