# Generated by Django 5.2.11 on 2026-08-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_alter_orderdelivery_delivery_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDEKCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(db_index=True, unique=True, verbose_name='Код населенного пункта СДЭК')),
                ('city_uuid', models.UUIDField(unique=True, verbose_name='UUID населенного пункта СДЭК')),
                ('city', models.CharField(db_index=True, max_length=255, verbose_name='Название населенного пункта')),
                ('fias_guid', models.UUIDField(blank=True, null=True, verbose_name='UUID ФИАС населенного пункта')),
                ('country_code', models.CharField(db_index=True, max_length=2, verbose_name='Код страны')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('region', models.CharField(db_index=True, max_length=255, verbose_name='Регион')),
                ('region_code', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Код региона СДЭК')),
                ('sub_region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Район региона')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('time_zone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Часовой пояс')),
                ('payment_limit', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Ограничение наложенного платежа')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Населенный пункт CDEK',
                'verbose_name_plural': 'Населенные пункты CDEK',
                'ordering': ['country_code', 'region', 'city'],
                'indexes': [models.Index(fields=['city', 'region', 'sub_region'], name='delivery_cd_city_67f9cc_idx'), models.Index(fields=['country_code', 'region_code'], name='delivery_cd_country_583148_idx')],
            },
        ),
    ]
