# Generated by Django 5.2.11 on 2026-08-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_cdekcity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDEKDeliveryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Код ПВЗ CDEK')),
                ('name', models.CharField(max_length=255, verbose_name='Название ПВЗ')),
                ('uuid', models.UUIDField(unique=True, verbose_name='UUID ПВЗ CDEK')),
                ('address_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к адресу')),
                ('nearest_station', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ближайшая остановка')),
                ('nearest_metro_station', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ближайшее метро')),
                ('work_time', models.CharField(blank=True, max_length=255, null=True, verbose_name='Время работы')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('type', models.CharField(db_index=True, max_length=50, verbose_name='Тип пункта')),
                ('owner_code', models.CharField(max_length=50, verbose_name='Код владельца')),
                ('take_only', models.BooleanField(default=False, verbose_name='Только выдача')),
                ('is_handout', models.BooleanField(default=False, verbose_name='Выдача заказов')),
                ('is_reception', models.BooleanField(default=False, verbose_name='Прием заказов')),
                ('is_dressing_room', models.BooleanField(default=False, verbose_name='Есть примерочная')),
                ('is_ltl', models.BooleanField(default=False, verbose_name='Поддерживает LTL')),
                ('have_cashless', models.BooleanField(default=False, verbose_name='Безналичная оплата')),
                ('have_cash', models.BooleanField(default=False, verbose_name='Наличная оплата')),
                ('have_fast_payment_system', models.BooleanField(default=False, verbose_name='Система быстрых платежей')),
                ('allowed_cod', models.BooleanField(default=False, verbose_name='Разрешен наложенный платеж')),
                ('office_image_list', models.JSONField(blank=True, default=list, verbose_name='Изображения ПВЗ')),
                ('work_time_list', models.JSONField(blank=True, default=list, verbose_name='Расписание работы')),
                ('work_time_exception_list', models.JSONField(blank=True, default=list, verbose_name='Исключения рабочего времени')),
                ('status', models.CharField(db_index=True, max_length=50, verbose_name='Статус ПВЗ')),
                ('country_code', models.CharField(db_index=True, max_length=2, verbose_name='Код страны')),
                ('region_code', models.IntegerField(db_index=True, verbose_name='Код региона CDEK')),
                ('region', models.CharField(db_index=True, max_length=255, verbose_name='Регион')),
                ('city_code', models.IntegerField(db_index=True, verbose_name='Код города CDEK')),
                ('city', models.CharField(db_index=True, max_length=255, verbose_name='Город')),
                ('postal_code', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Почтовый индекс')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес')),
                ('address_full', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Полный адрес')),
                ('city_uuid', models.UUIDField(verbose_name='UUID города CDEK')),
                ('ltl_acceptance_partners', models.BooleanField(default=False, verbose_name='Прием LTL партнерами')),
                ('ltl_issuance_partners', models.BooleanField(default=False, verbose_name='Выдача LTL партнерами')),
                ('fulfillment', models.BooleanField(default=False, verbose_name='Fulfillment')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Пункт выдачи CDEK',
                'verbose_name_plural': 'Пункты выдачи CDEK',
                'ordering': ['country_code', 'region', 'city', 'name'],
                'indexes': [models.Index(fields=['city', 'region'], name='delivery_cd_city_cbf22d_idx'), models.Index(fields=['country_code', 'region_code'], name='delivery_cd_country_5edc9d_idx'), models.Index(fields=['city_code'], name='delivery_cd_city_co_d09bec_idx'), models.Index(fields=['status', 'is_active'], name='delivery_cd_status_8335fa_idx')],
            },
        ),
    ]
