# Generated by Django 5.2.11 on 2026-08-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_cdekdeliverypoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdekdeliverypoint',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='cdekdeliverypoint',
            name='address_full',
            field=models.TextField(blank=True, null=True, verbose_name='Полный адрес'),
        ),
        migrations.AlterField(
            model_name='cdekdeliverypoint',
            name='nearest_metro_station',
            field=models.TextField(blank=True, null=True, verbose_name='Ближайшее метро'),
        ),
        migrations.AlterField(
            model_name='cdekdeliverypoint',
            name='nearest_station',
            field=models.TextField(blank=True, null=True, verbose_name='Ближайшая остановка'),
        ),
    ]
