# Generated by Django 5.2.11 on 2026-08-24 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_alter_cdekdeliverypoint_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdekdelivery',
            name='cdek_office_code_from',
        ),
        migrations.RemoveField(
            model_name='cdekdelivery',
            name='cdek_office_code_to',
        ),
        migrations.AddField(
            model_name='cdekdelivery',
            name='delivery_mode',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Код режима доставки CDEK'),
        ),
        migrations.AddField(
            model_name='cdekdelivery',
            name='delivery_mode_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Режим доставки CDEK'),
        ),
        migrations.AddField(
            model_name='cdekdelivery',
            name='delivery_point',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ПВЗ получения CDEK'),
        ),
        migrations.AddField(
            model_name='cdekdelivery',
            name='from_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес отправления'),
        ),
        migrations.AddField(
            model_name='cdekdelivery',
            name='from_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_deliveries', to='delivery.cdekcity', verbose_name='Город отправления CDEK'),
        ),
        migrations.AddField(
            model_name='cdekdelivery',
            name='from_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Почтовый индекс отправления'),
        ),
        migrations.AddField(
            model_name='cdekdelivery',
            name='shipment_point',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ПВЗ отправления CDEK'),
        ),
        migrations.AddField(
            model_name='cdekdelivery',
            name='to_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес получения'),
        ),
        migrations.AddField(
            model_name='cdekdelivery',
            name='to_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_deliveries', to='delivery.cdekcity', verbose_name='Город получения CDEK'),
        ),
        migrations.AddField(
            model_name='cdekdelivery',
            name='to_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Почтовый индекс получения'),
        ),
    ]
