# Generated by Django 5.2.11 on 2026-08-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_remove_cdekdelivery_cdek_office_code_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cdekdelivery',
            old_name='from_address',
            new_name='address_from',
        ),
        migrations.RenameField(
            model_name='cdekdelivery',
            old_name='from_postal_code',
            new_name='postal_code_from',
        ),
        migrations.RemoveField(
            model_name='cdekdelivery',
            name='from_city',
        ),
        migrations.RemoveField(
            model_name='cdekdelivery',
            name='to_address',
        ),
        migrations.RemoveField(
            model_name='cdekdelivery',
            name='to_city',
        ),
        migrations.RemoveField(
            model_name='cdekdelivery',
            name='to_postal_code',
        ),
        migrations.AddField(
            model_name='cdekdelivery',
            name='address_to',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес отправления'),
        ),
        migrations.AddField(
            model_name='cdekdelivery',
            name='location_from',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Город отправления магазина'),
        ),
        migrations.AddField(
            model_name='cdekdelivery',
            name='location_from_country',
            field=models.CharField(blank=True, default='Россия', max_length=255, null=True, verbose_name='Страна магазина'),
        ),
        migrations.AddField(
            model_name='cdekdelivery',
            name='location_from_district',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Район магазина'),
        ),
        migrations.AddField(
            model_name='cdekdelivery',
            name='location_from_region',
            field=models.CharField(default=1, max_length=255, verbose_name='Область/регион магазина'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cdekdelivery',
            name='location_to',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Город отправления магазина'),
        ),
        migrations.AddField(
            model_name='cdekdelivery',
            name='location_to_country',
            field=models.CharField(blank=True, default='Россия', max_length=255, null=True, verbose_name='Страна магазина'),
        ),
        migrations.AddField(
            model_name='cdekdelivery',
            name='location_to_district',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Район магазина'),
        ),
        migrations.AddField(
            model_name='cdekdelivery',
            name='location_to_region',
            field=models.CharField(default=1, max_length=255, verbose_name='Область/регион магазина'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cdekdelivery',
            name='postal_code_to',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Почтовый индекс отправления'),
        ),
    ]
