# Generated by Django 5.2.11 on 2026-08-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_rename_from_address_cdekdelivery_address_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdekdelivery',
            name='address_to',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес получателя'),
        ),
        migrations.AlterField(
            model_name='cdekdelivery',
            name='location_to',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Город получателя'),
        ),
        migrations.AlterField(
            model_name='cdekdelivery',
            name='location_to_country',
            field=models.CharField(blank=True, default='Россия', max_length=255, null=True, verbose_name='Страна получателя'),
        ),
        migrations.AlterField(
            model_name='cdekdelivery',
            name='location_to_district',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Район получателя'),
        ),
        migrations.AlterField(
            model_name='cdekdelivery',
            name='location_to_region',
            field=models.CharField(max_length=255, verbose_name='Область/регион получателя'),
        ),
        migrations.AlterField(
            model_name='cdekdelivery',
            name='postal_code_to',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Почтовый индекс получателя'),
        ),
    ]
