# Generated by Django 5.2.11 on 2026-09-07 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_alter_cdekdelivery_address_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CdekDeliveryStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(max_length=100)),
                ('status_name', models.CharField(blank=True, max_length=255)),
                ('status_date', models.DateTimeField()),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cdek_delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='delivery.cdekdelivery')),
            ],
            options={
                'ordering': ['status_date'],
            },
        ),
        migrations.CreateModel(
            name='CdekRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_uuid', models.UUIDField(blank=True, null=True)),
                ('request_type', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('response_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cdek_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_logs', to='delivery.cdekdelivery')),
            ],
        ),
    ]
