# Generated by Django 5.2.11 on 2026-09-07 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_cdekdeliverystatushistory_cdekrequestlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cdekrequestlog',
            old_name='request_uuid',
            new_name='cdek_uuid',
        ),
    ]
