# Generated by Django 5.2.11 on 2026-09-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_rename_request_uuid_cdekrequestlog_cdek_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdekdelivery',
            name='stock_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Зарезервирован'), (2, 'Подтверждён'), (3, 'Возвращён')], default=1),
        ),
    ]
