# Generated by Django 5.2.11 on 2026-09-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_cdekdelivery_stock_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdelivery',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'В обработке'), (2, 'Подтверждена'), (3, 'В пути'), (4, 'Доставлена'), (5, 'Ошибка'), (6, 'Отменена')], default=1),
        ),
    ]
