# Generated by Django 5.2.11 on 2026-09-14 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0016_orderdelivery_status'),
        ('order', '0006_returnrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CdekReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdek_uuid', models.UUIDField(unique=True, verbose_name='UUID возврата CDEK')),
                ('tariff_code', models.PositiveIntegerField(verbose_name='Тариф CDEK')),
                ('request_state', models.CharField(blank=True, max_length=50, null=True, verbose_name='Состояние запроса CDEK')),
                ('cdek_status_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код статуса CDEK')),
                ('cdek_status_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус CDEK')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cdek_delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='delivery.cdekdelivery', verbose_name='Исходная доставка CDEK')),
                ('return_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cdek_return', to='order.returnrequest', verbose_name='Заявка на возврат')),
            ],
        ),
    ]
