# Generated by Django 5.2.11 on 2026-08-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_location_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location_to_country',
            field=models.CharField(default='Россия', max_length=255, verbose_name='Страна получателя'),
        ),
        migrations.AddField(
            model_name='user',
            name='location_to_district',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Район получателя'),
        ),
        migrations.AddField(
            model_name='user',
            name='location_to_region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Область/регион получателя'),
        ),
    ]
