# Generated by Django 5.2.11 on 2026-08-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_location_to_country_user_location_to_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location_to',
            field=models.CharField(max_length=255, verbose_name='Город получателя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location_to_region',
            field=models.CharField(max_length=255, verbose_name='Область/регион получателя'),
        ),
    ]
