

services:
  db:
    image: postgres:14.8
    env_file:
      - .env
    ports:
      - "65432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    env_file:
      - .env
    command: sh -c "python manage.py migrate && python manage.py load_mock_roles && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis

  celery:
    build: .
    env_file:
      - .env
    command: celery -A delivery_service worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    env_file:
      - .env
    command: celery -A delivery_service beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis

volumes:
  postgres_data:

