

services:
  db:
    image: postgres:14.8
    env_file:
      - .env
    ports:
      - "65432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  kafka1:
    image: bitnami/kafka:3.7
    restart: always
    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_KRAFT_CLUSTER_ID: A370i42nQuCtnpFN-7I41Q

      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_CFG_LISTENERS: CLIENT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka1:9092

      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: CLIENT

      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"

      ALLOW_PLAINTEXT_LISTENER: "yes"

    volumes:
      - kafka_data:/bitnami/kafka

  kafka-init:
    image: bitnami/kafka:3.7
    depends_on:
      - kafka1
    command: >
      /bin/bash -c '
        set -e;
        echo "Waiting for Kafka...";
        until kafka-topics.sh --bootstrap-server kafka1:9092 --list >/dev/null 2>&1; do
          sleep 2;
        done;
        echo "Creating Kafka topics...";
        kafka-topics.sh --bootstrap-server kafka1:9092 --create --if-not-exists --topic cdek.order.accepted --partitions 1 --replication-factor 1;
        kafka-topics.sh --bootstrap-server kafka1:9092 --create --if-not-exists --topic cdek.order.ready --partitions 1 --replication-factor 1;
        kafka-topics.sh --bootstrap-server kafka1:9092 --create --if-not-exists --topic cdek.order.failed --partitions 1 --replication-factor 1;
        echo "Kafka topics initialized";
      '

  web:
    build: .
    env_file:
      - .env
    command: sh -c "python manage.py migrate && python manage.py load_mock_roles && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis
      - kafka-init
      - kafka1

  celery:
    build: .
    env_file:
      - .env
    command: celery -A delivery_service worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - kafka-init
      - kafka1

  celery-beat:
    build: .
    env_file:
      - .env
    command: celery -A delivery_service beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis

volumes:
  postgres_data:
  kafka_data:
