# Generated by Django 5.2.11 on 2026-07-28 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_alter_cdektariff_weight_max_and_more'),
        ('seller', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDeliverySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_settings', to='seller.shop')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_settings', to='delivery.cdektariff')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('shop', 'tariff'), name='unique_shop_tariff')],
            },
        ),
    ]
