# Generated by Django 5.2.11 on 2026-08-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_shopdeliverysetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='carrier',
            field=models.IntegerField(choices=[(1, 'СДЭК'), (2, 'Boxberry')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='location_from',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
