# Generated by Django 5.2.11 on 2026-08-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_sellerrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='location_from_country',
            field=models.CharField(default='Россия', max_length=255, verbose_name='Страна магазина'),
        ),
        migrations.AddField(
            model_name='shop',
            name='location_from_district',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Район магазина'),
        ),
        migrations.AddField(
            model_name='shop',
            name='location_from_region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Область/регион магазина'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='location_from',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Город отправления магазина'),
        ),
    ]
