# Generated by Django 5.2.11 on 2026-08-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_shop_location_from_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='location_from',
            field=models.CharField(max_length=255, verbose_name='Город отправления магазина'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='location_from_region',
            field=models.CharField(max_length=255, verbose_name='Область/регион магазина'),
        ),
    ]
