# Generated by Django 5.2.11 on 2026-08-26 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_remove_cdekdelivery_cdek_office_code_from_and_more'),
        ('seller', '0007_alter_shop_location_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.CharField(default='не указан', max_length=255, verbose_name='Адрес отправления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='postal_code',
            field=models.CharField(default=0, max_length=20, verbose_name='Почтовый индекс отправления'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CDEKShopDeliverySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cdek_delivery_settings', to='seller.shop')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cdek_shop_settings', to='delivery.cdektariff')),
            ],
        ),
        migrations.DeleteModel(
            name='ShopDeliverySetting',
        ),
        migrations.AddConstraint(
            model_name='cdekshopdeliverysetting',
            constraint=models.UniqueConstraint(fields=('shop', 'tariff'), name='unique_shop_tariff'),
        ),
    ]
