# Generated by Django 5.2.11 on 2026-08-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_shop_address_shop_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shipment_point',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ПВЗ отправления ТК'),
        ),
    ]
