# Generated by Django 5.2.11 on 2026-08-31 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_shop_shipment_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='shipment_point',
            new_name='delivery_point',
        ),
    ]
