# Generated by Django 5.2.11 on 2026-09-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_rename_shipment_point_shop_delivery_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='delivery_point',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ПВЗ или постамат отправления ТК'),
        ),
    ]
