# Generated by Django 5.2.11 on 2026-09-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_alter_shop_delivery_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='phone_number',
            field=models.CharField(default=79955223269, max_length=20, verbose_name='Телефон магазина'),
            preserve_default=False,
        ),
    ]
