# Generated by Django 5.2.11 on 2026-09-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'В обработке'), (2, 'Подтверждён'), (3, 'Частично с ошибкой'), (4, 'Частично доставлен'), (5, 'Завершён'), (6, 'Ошибка'), (7, 'Отменён')], default=1),
        ),
    ]
