# Generated by Django 5.2.11 on 2026-09-14 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0016_orderdelivery_status'),
        ('order', '0005_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'На рассмотрении'), (2, 'Одобрена'), (3, 'Отклонена')], default=1, verbose_name='Статус заявки')),
                ('reason', models.TextField(verbose_name='Причина возврата')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Причина отказа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to='delivery.orderdelivery', verbose_name='Доставка заказа')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
        ),
    ]
